exclude: '^data/|.env'
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: license-header
        name: License Header
        entry: ./scripts/license.py
        language: system
        always_run: true
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args:
          - '--baseline'
          - '.secrets.baseline'
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0a6
    hooks:
      - id: sqlfluff-fix
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.17.0
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
