name: Lint, Build & Test

on: [push, pull_request]

env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  lint-build-test:
    name: Lint, Build & Test
    uses: spyderorg/workflows/.github/workflows/make-build-nix.yml@main
    secrets: inherit # pragma: allowlist secret
