name: "tagged-release"

on:
  push:
    tags:
      - "v*"
env:
  GH_ACCESS_TOKEN: ${{ secrets.GH_PAT }}

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    name: Tagged Release
    uses: devnw/workflows/.github/workflows/make-release.yml@main
    secrets: inherit # pragma: allowlist secret
