name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "Build & Unit Tests"
    strategy:
      matrix:
        go-version: [1.18.0-beta1]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: false
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -race -failfast ./...
  codeql:
    name: "CodeQL Check"
    needs: [build]
    strategy:
      matrix:
        go-version: [1.18.0-beta1]
        platform: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: true
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  release:
    needs: [build, codeql]
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Github Release from Tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE